---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=1"
          - "--no-sort-keys"
      - id: detect-private-key
      - id: check-case-conflict
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      # - id: detect-aws-credentials
      - id: check-docstring-first
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: v3.3.5
    hooks:
      - id: pylint
        additional_dependencies: ["requests", "sqlglot", "pandas", "pytest", "jmespath", "python-dotenv", "polars"]
        args: [
                  # E1101: Instance of 'LookupDict' has no 'ok' member (no-member)
                  '--generated-member=requests.codes.ok'
              ]
  # https://github.com/python/mypy/issues/13916
  # https://jaredkhan.com/blog/mypy-pre-commit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: f40886d54c729f533f864ed6ce584e920feb0af7  # 1.15.0
    hooks:
      - id: mypy
        language: system
        pass_filenames: false
        args: ['.']
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        # args: [-I, .codespellignore]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        # exclude: .*/tests/.*
  - repo: local
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks/issues/683
      # https://github.com/Lucas-C/pre-commit-hooks#forbid--remove-some-unicode-characters
      - id: forbid-unicode-non-breaking-spaces
        name: Detect unicode non-breaking space character U+00A0 aka M-BM-
        language: system
        entry: perl -ne 'print if $m = /\xc2\xa0/; $t ||= $m; END{{exit $t}}'
        files: ''
      - id: remove-unicode-non-breaking-spaces
        name: Remove unicode non-breaking space character U+00A0 aka M-BM-
        language: system
        entry: perl -pi* -e 's/\xc2\xa0/ /g && ($t = 1) && print STDERR $_; END{{exit
          $t}}'
        files: ''
      - id: forbid-en-dashes
        name: Detect the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -ne 'print if $m = /\xe2\x80\x93/; $t ||= $m; END{{exit $t}}'
        files: ''
      - id: remove-en-dashes
        name: Remove the EXTREMELY confusing unicode character U+2013
        language: system
        entry: perl -pi* -e 's/\xe2\x80\x93/-/g && ($t = 1) && print STDERR $_; END{{exit
          $t}}'
        files: ''
      - id: gitleaks
        name: Gitleaks
        entry: bash -c 'gitleaks detect --source . -v'
        language: system
        stages: ["pre-commit", "pre-push"]
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
        # For running trufflehog in docker, use the following entry instead:
        # entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["pre-commit", "pre-push"]
